/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.codelab;

public class App {

    public static void main(String[] args) {
        System.out.println("No application implemented so far!");
    }
}
